version: "3.8"

services:
  web:
    image: ${DOCKER_IMAGE:-kmaxi/vow-website:latest}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - WEBSITE_DB_HOST=website
      - WEBSITE_DB_NAME=website
      - WEBSITE_DB_USER=${DB_USER}
      - WEBSITE_DB_PASSWORD=${DB_PASSWORD}
      - API_DB_HOST=api
      - API_DB_NAME=api
      - API_DB_USER=${DB_USER}
      - API_DB_PASSWORD=${DB_PASSWORD}
      - LINE_REPORT_COLLECT=${LINE_REPORT_COLLECT}
      - LINE_REPORT_MODIFY=${LINE_REPORT_MODIFY}
      - STATISTICS_AGGREGATE=${STATISTICS_AGGREGATE}
      - DISCORD_INTEGRATION=${DISCORD_INTEGRATION}
      - PREMIUM_AUTHENTICATION=${PREMIUM_AUTHENTICATION}
      - ADMINER_HOST=adminer
      - ADMINER_PORT=8080
    depends_on:
      - website
      - api
      - adminer
    volumes:
      - dynamic_data:/var/www/html/dynamic
      - /etc/letsencrypt/live/voicesofwynn.com:/etc/letsencrypt/live/voicesofwynn.com:ro
      - /etc/letsencrypt/archive/voicesofwynn.com:/etc/letsencrypt/archive/voicesofwynn.com:ro
      - ${PWD}/logs:/var/log
    env_file:
      - .env
    networks:
      - app_network

  website:
    image: mariadb:10.5.24
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: website
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - website_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app_network

  api:
    image: mariadb:10.5.24
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: api
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - api_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app_network

  adminer:
    image: adminer
    # Remove the public port binding as we'll access it through the web service
    # ports:
    #   - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - website
      - api
    networks:
      - app_network

volumes:
  website_data:
  api_data:
  dynamic_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/dynamic

# Add this networks section to define the network
networks:
  app_network:
    driver: bridge
