<nav class="adnav">
    <a href="/administration/accounts"> Account management </a>
    <a href="/administration/new-account"> Create new account </a>
    <a href="/administration/new-quest"> Create new quest </a>
    <a href="/administration/new-npc"> Create new NPC </a>
    <a href="/administration/npcs"> Manage NPCs </a>
    <a href="/administration/upload"> Upload recordings </a>
</nav>

<?php require $this->getNextView(); ?>

