<!DOCTYPE HTML>
<html lang="en">
<head>
    <base href="/" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" />
    <title><?= ${basename(__FILE__, '.phtml').'_title'} ?></title>
    <meta name="description" content="<?= ${basename(__FILE__, '.phtml').'_description'} ?>" />
    <meta name="keywords" content="<?= ${basename(__FILE__, '.phtml').'_keywords'} ?>" />
    <!-- Icons -->
    <link rel="apple-touch-icon" sizes="180x180" href="images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="images/favicon-16x16.png">
    <link rel="manifest" href="site.webmanifest">
    <link rel="mask-icon" href="images/safari-pinned-tab.png" color="#a340c4">
    <link rel="shortcut icon" href="images/favicon.ico">
    <meta name="msapplication-TileColor" content="#7b1a9b">
    <meta name="msapplication-config" content="browserconfig.xml">
    <meta name="theme-color" content="#7b1a9b">
    
    <!-- Stylesheets -->
    <?php foreach (self::$cssFiles as $cssFile) : ?>
        <link rel="stylesheet" type="text/css" href="css/<?= $cssFile ?>.css">
    <?php endforeach ?>
</head>
<body>
    <header>
        <nav>
            <a href="/">Home</a>
            <a href="/credits">Credits</a>
            <?php if (!isset($_SESSION['user'])) : ?><a href="/login">Login</a><?php endif ?>
            <?php if (isset($_SESSION['user']) && $_SESSION['user']->isSysAdmin()) : ?><a href="/administration">Administration</a><?php endif ?>
            <?php if (isset($_SESSION['user'])) : ?><a href="/account">My Account</a><?php endif ?>
            <?php if (isset($_SESSION['user'])) : ?><a href="/logout">Logout</a><?php endif ?>
        </nav>
    </header>
    <main>
        <?php require $this->getNextView(); ?>
    </main>
    <footer>
        <a target='_blank' rel="noopener" href="https://discord.gg/7TwxdtVqHq">Join our Discord</a>
        <span id="about">&copy Shady, <?= ${basename(__FILE__, '.phtml').'_currentYear'} ?></span>
    </footer>
    <!-- JavaScript -->
    <?php foreach (self::$jsFiles as $jsFile) : ?>
        <script type="text/javascript" src="js/<?= $jsFile ?>.js"></script>
    <?php endforeach ?>
</body>
</html>