<!DOCTYPE HTML>
<html lang="en">
<head>
    <base href="/" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" />
    <title><?= ${basename(__FILE__, '.phtml').'_title'} ?></title>
    <meta name="description" content="<?= ${basename(__FILE__, '.phtml').'_description'} ?>" />
    <meta name="keywords" content="<?= ${basename(__FILE__, '.phtml').'_keywords'} ?>" />
    <!-- Icons -->
    <link rel="apple-touch-icon" sizes="180x180" href="images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="images/favicon-16x16.png">
    <link rel="manifest" href="site.webmanifest">
    <link rel="mask-icon" href="images/safari-pinned-tab.png" color="#a340c4">
    <link rel="shortcut icon" href="images/favicon.ico">
    <meta name="msapplication-TileColor" content="#7b1a9b">
    <meta name="msapplication-config" content="browserconfig.xml">
    <meta name="theme-color" content="#7b1a9b">
    
    <!-- Stylesheets -->
    <?php foreach (self::$cssFiles as $cssFile) : ?>
        <link rel="stylesheet" type="text/css" href="css/<?= $cssFile ?>.css">
    <?php endforeach ?>
</head>

<body>
    <div class="header0">
        <ul class="nav">
            <div style="float: left">
                <li><a style="border-left: none"href="/"> Home </a></li>
                <li><a href="/downloads"> Downloads </a></li>
                <li><a style="border-right: none" href="/faq">FAQ </a></li>
            
                    <li><a target='_blank' rel="noopener" href="https://www.patreon.com/Voices_Of_Wynn"><img src="images/patreon.png" alt="Patreon logo" width="20px" height="20px"/> Patreon</a></li>
                    <li><a style="border-right: none" target='_blank' rel="noopener" href="https://discord.gg/kuEK3XH4Y5"><img src="images/discord.png" alt="Discord logo" width="20px" height="20px"/> Discord</a></li>
            </div>
        </ul>
        <div id="vertical"></div>
            <a href="" class="imglink">
                <img class="logo" src="images/wynnvplogo.png" alt="Very cool Logo" width="200px" height="200px"/>
            </a>
    </div>
    
<!-- <center> -->
    <main>
        <?php require $this->getNextView(); ?>
    </main>
<!-- </center> -->
    <footer style="font-weight: bolder;">
        <span id="about">Coded by &copy; <a href="https://github.com/ShadyMedic">Shady</a>, <?= ${basename(__FILE__, '.phtml').'_currentYear'} ?></span>
        <span style="float: right"> designed with &hearts; by <a href="https://www.just5moreminutes.xyz">Just5MoreMinutes</a></span> <!-- (◡︵◡) -->
    </footer>
    <!-- JavaScript -->
    <?php foreach (self::$jsFiles as $jsFile) : ?>
        <script type="text/javascript" src="js/<?= $jsFile ?>.js"></script>
    <?php endforeach ?>
</body>
</html>