<?php $voiceActor = ${basename(__FILE__, '.phtml').'_voice_actor'}; ?>
<h1><?= $voiceActor->getName(); ?></h1>
<?php if (!empty($voiceActor->getSocial('discord'))) : ?>
  <h6 class="txt-c txt-main">
      <div id='discord-container'>
        <img src="images/discord_icon.png" alt="Discord icon" width="3.125rem" height="3.125rem"/>
        <span class="vertical-bottom-text-span arial" id="discord-tag-cast"><?= $voiceActor->getSocial('discord') ?></span>
    </div>
  </h6>
<?php endif ?>

<hr class="hr-f">

<section>   <!-- "bio" has no styling?!??! interesting... -->
    <div id="socials-container">
        <div class="socials-row txt-c" id="scoials-row-1">
            <div class="socials-card">  <!-- "socials-card" has no styling, will keep for later if someone needs it -->
                <img class="contributor-img" src="dynamic/avatars/<?= $voiceActor->getAvatarLink() ?>" alt="Voice actor's avatar">

                <?php if (!empty($voiceActor->getEmail()) && $voiceActor->hasPublicEmail()) : ?>
                    <br>
                    <a href="mailto:<?= $voiceActor->getEmail() ?>"><button class="contactbtn">
                        ✉ Contact
                    </button></a>
                <?php endif ?>
            </div>
        </div>
                
        <div class="socials-row txt-c" id="socials-row-2">
            <?php if (!empty($voiceActor->getSocial('youtube'))) : ?>
            <div>
                <a href="<?= $voiceActor->getSocial('youtube') ?>" target="_blank" class="youtube">
                <span class="txt-c">
                    <img src="images/youtube_icon.png" alt="YouTube icon" /><br>
                    <button class="youtubebtn">
                        YouTube
                    </button>
                </span>
                </a>
            </div>
            <?php endif ?>
            <?php if (!empty($voiceActor->getSocial('twitter'))) : ?>
            <div class="socials-card">
                <a href="https://twitter.com/<?= $voiceActor->getSocial('twitter') ?>" target="_blank" class="twitter">
                <span class="txt-c">
                    <img src="images/twitter_icon.png" alt="Twitter icon" /><br>
                    <button class="twitterbtn">
                        @<?= $voiceActor->getSocial('twitter') ?>
                    </button>
                </span>
                </a>
            </div>
            <?php endif ?>
            <?php if (!empty($voiceActor->getSocial('castingcallclub'))) : ?>
            <div class="socials-card">
                <a href="https://castingcall.club/<?= $voiceActor->getSocial('castingcallclub') ?>" target="_blank"     class="castingcallclub">
                <span class="txt-c">
                    <img src="images/castingcallclub_icon.png" alt="Casting Call Club icon" /><br>
                    <button class="castingcallclubbtn">
                        <?= $voiceActor->getSocial('castingcallclub') ?>
                    </button>
                </span>
                </a>
            </div>
            <?php endif ?>
        </div>
    </div>
    
    <hr>
    <article class="wb-a txt-c"><?= $voiceActor->getBio(); ?></article>
    <hr class="hr-f">
</section>
<section>
    <h3 class="txt-c">Recordings</h3>
    <?php if (count(${basename(__FILE__, '.phtml').'_quest_recordings'}) === 0) : ?>
    <i class="txt-c">This contributor didn't submit any recordings.</i>
    <?php endif ?>
    <?php foreach (${basename(__FILE__, '.phtml').'_quest_recordings'} as $quest) : ?>
    <div class="reccenter">
        <section>
            <table>
                <tr>
                  <th colspan="5">
                      <b><?= $quest->getNpcs()[0]->getName() ?></b> in <i><?= $quest->getName() ?></i>
                  </th>
                </tr>
                <?php $recordings = $quest->getNpcs()[0]->getRecordings(); ?>
                <?php foreach ($recordings as $recording) : ?>
                    <tr>
                      <td># <?= $recording->line ?></td>
                      <td>
                          <audio controls>
                              <source src="dynamic/recordings/<?= $recording->file ?>" type="audio/ogg">
                              Oops! Your browser doesnt support the OGG format :(
                          </audio>
                      <td>
                          <button class="upvote<?php if (in_array($recording->id, ${basename(__FILE__, '.phtml').'_upvoted'})) : ?> clicked<?php endif ?>" data-recording-id="<?= $recording->id ?>" data-npc-id="<?= $recording->npcId ?>">👍 <span><?= $recording->upvotes ?></span></button>
                      </td>
                      <td>
                          <button class="downvote<?php if (in_array($recording->id, ${basename(__FILE__, '.phtml').'_downvoted'})) : ?> clicked<?php endif ?>" data-recording-id="<?= $recording->id ?>" data-npc-id="<?= $recording->npcId ?>">👎 <span><?= $recording->downvotes ?></span></button>
                      </td>
                      <td>
                          <a href="contents/npc/<?= $recording->npcId ?>/comments/<?= $recording->id ?>"><button class="commentbtn">💬 <span><?= $recording->comments ?></span></button></a>
                      </td>
                    </tr>
                <?php endforeach ?>
            </table>
        </section>
    </div>
</section>
<?php endforeach ?>
<br>
<button class="backbtn" onclick="history.go(-1)">< Go Back</button>