<script>
    var npcId = <?= ${basename(__FILE__, '.phtml').'_recording'}->npcId ?>;
    var voiceActorId = <?= ${basename(__FILE__, '.phtml').'_voice_actor_id'} ?>;
    var userId = "<?= @${basename(__FILE__, '.phtml').'_user_id'} ?>";
    var userName = "<?= @${basename(__FILE__, '.phtml').'_user_name'} ?>";
    var userAvatar = "<?= @${basename(__FILE__, '.phtml').'_user_avatar'} ?>";
</script>


<h1>Comment Section</h1>
<h3 class="txt-c"><?= ${basename(__FILE__, '.phtml').'_recording_title'} ?></h3>

<p class="txt-c mb-m">
    <audio controls preload="none">
        <source src="dynamic/recordings/<?= ${basename(__FILE__, '.phtml').'_recording'}->file ?>" type="audio/ogg">
        Oops! Your browser doesnt support the OGG format :(
    </audio>
</p>

<p class="txt-c">
    <button id="new-comment-button">Post new Comment</button>
</p>

<hr class="hr-f">

<p class="txt-c">
    <button id="hide-form-button">Hide the form</button>
</p>

<form method="post" data-recording-id="<?= ${basename(__FILE__, '.phtml').'_recording'}->id ?>">
<fieldset class="comment-writing-form">

<?php if (${basename(__FILE__, '.phtml').'_logged_in'}) : ?>
<div>
    <div id="contributor-option" class="comment-tab selected as-contributor">Post as a contributor</div>
    <div id="guest-option" class="comment-tab as-guest">Post as a guest</div>
</div>
<div id="contributor-form" class="comment-form-wrapper">
    <fieldset class="default-bg comment-field mb-m">
        <label for="content-contributor" class="lb-a">Comment: </label>
        <textarea id="content-contributor" placeholder="You can praise the voice actor, suggest what could be improved or just say how much you like this quest. Just please, keep bad words out of that 😉"></textarea>
    </fieldset>
    <input type="submit" value="Send" />
    <small class="comment-disclaimer">
        Name and contents of the comment will be publicly visible.<br>
        The comment will be linked to your account and you'll be able to delete it anytime.
    </small>
</div>
<?php endif ?>

<div id="guest-form" <?php if (${basename(__FILE__, '.phtml').'_logged_in'}) : ?>class="display-none"<?php endif ?>>
	<?php if (!${basename(__FILE__, '.phtml').'_logged_in'}) : ?>
        <span class="comment-disclaimer">Are you a contributor? You can post a verified comment after <a href="login">logging in</a>.</span>
	<?php endif ?>
    <fieldset class="comment-field">
        <label for="name">Name: </label><input id="name" type="text" placeholder="Anonymous" class="mb-l"/>
        <label for="email">E-mail: </label><input id="email" type="text" placeholder="Used to get Gravatar; not required" class="mb-l" />
        <label for="content-guest" class="mb-l">Comment: </label>
        <textarea id="content-guest" placeholder="You can praise the voice actor, suggest what could be improved or just say how much you like this quest. Just please, keep bad words out of that 😉"></textarea>
    </fieldset>
    <label for="antispam" class="mb-l">Not a robot? Then you can select some shade of <strong style="color:<?= ${basename(__FILE__, '.phtml').'_antispam_color_code'} ?>;"><?= ${basename(__FILE__, '.phtml').'_antispam_color'} ?></strong>, right?</label>
    <input id="antispam" type="color" required />
    <input type="submit" value="Send" class="mt-d"/>
    <small class="comment-disclaimer">
        Name and contents of the comment will be publicly visible.<br>
        You will be able to delete this comment only from this IP.<br>
        Your IP and e-mail addresses and will be stored, but will never be publicly visible.
    </small>
</div>
</fieldset>
</form>

<div id="comments" class="m-a">
<?php foreach (${basename(__FILE__, '.phtml').'_comments'} as $comment) : ?>
<div class="comment mt-m" id="c<?= $comment->id ?>">
    <table class="comment-box">

        <tbody>

        <tr>

            <td rowspan="0" class="comment-picture">
                <img src="<?= $comment->getAvatar() ?>" alt="Avatar" class="comment-avatar" width="80px" height="80px"/>
            </td>

                <td class="comment-main-column user-username pt-s">
                    <strong>
                        <?php if ($comment->verified) : ?>
                            <a href="cast/<?= $comment->userId ?>"><?= $comment->getName() ?></a>
                        <?php else : ?>
                            <p class="pt-m"><?= $comment->getName() ?></p>
                        <?php endif ?>
                    </strong>
                    <?php if ($comment->verified) : ?>
                        <?php if ($comment->userId === ${basename(__FILE__, '.phtml').'_voice_actor_id'}) : ?>
                            <div class="author-badge" title="This user is the author of this recording.">Author</div>
                        <?php endif ?>
                        <div class="contributor-badge" title="This user contributed to this project.">Contributor</div>
                    <?php endif ?>
                </td>

                <td class="comment-deletion">
                    <?php if (${basename(__FILE__, '.phtml').'_admin'} || in_array($comment->id, ${basename(__FILE__, '.phtml').'_owned_comments'})) : ?>
                        <button data-comment-id="<?= $comment->id ?>" class="delete-comment-button">×</button>
                    <?php endif ?>
                </td>
            </tr>

            <tr>
                <td colspan="2" class="comment-content-separator"></td>
            <tr>

                <td class="no-m no-p comment-main-content" colspan="2">

                    <div class="comment-content">
                        <p class="no-m max-width"><?= $comment->content ?></p>
                    </div>

                </td>
            </tr>

        </tbody>

    </table>
</div>
<?php endforeach ?>

</div>

<br>
<button class="backbtn" onclick="history.go(-1)">< Go Back</button>
