<script>var npcId = <?= ${basename(__FILE__, '.phtml').'_recording'}->npcId ?>;</script>

<h1>Comment section</h1>
<h3><?= ${basename(__FILE__, '.phtml').'_recording_title'} ?></h3>
<audio controls>
    <source src="dynamic/recordings/<?= ${basename(__FILE__, '.phtml').'_recording'}->file ?>" type="audio/ogg">
    Oops! Your browser doesnt support the OGG format :(
</audio>
<br>
<button id="new-comment-button">Post new comment</button>
<button id="hide-form-button">Hide the form</button>
<form method="post" data-recording-id="<?= ${basename(__FILE__, '.phtml').'_recording'}->id ?>">
<fieldset>
<fieldset>
    <label for="name">Name: </label><input id="name" name="name" type="text" placeholder="Anonymous" /><br>
    <label for="email">E-mail: </label><input id="email" name="name" type="text" placeholder="(not required)" /><br>
    <label for="content">Comment: </label><br>
    <textarea id="content" name="content" placeholder="You can praise the voice actor, suggest what could be improved or just say how much you like this quest. Just please, keep bad words out of that 😉" required></textarea>
</fieldset>
    <label for="antispam">Not a robot? Then you can select some shade of <strong style="color:<?= ${basename(__FILE__, '.phtml').'_antispam_color_code'} ?>;"><?= ${basename(__FILE__, '.phtml').'_antispam_color'} ?></strong>, right?</label><br>
    <input id="antispam" name="antispam" type="color" required />
    <input type="submit" value="Send" />
    <small>
        Name, e-mail and contents of the comment will be publicly visible and you won't be able to edit or
        delete the comment by yourself.
    </small>
</fieldset>
</form>
<div id="comments">
<?php foreach (${basename(__FILE__, '.phtml').'_comments'} as $comment) : ?>
<div class="card">
    <table>
        <tr>
            <td rowspan="2"><img src="<?= $comment->gravatar ?>" alt="Avatar" /></td>
            <td>
                <span><strong><?= $comment->name ?></strong> < <?= $comment->email ?> ></span>
                <?php if (${basename(__FILE__, '.phtml').'_admin'}) : ?>
                <button data-comment-id="<?= $comment->id ?>" class="delete-comment-button">×</button>
                <?php endif ?>
            </td>
        </tr>
        <tr><td><div class="comment-content"><?= $comment->content ?></div></td></tr>
    </table>
</div>
<?php endforeach ?>
</div>

<br>
<a href="/credits"><button class="backbtn">< Go Back</button></a>