<h1>Mod Contents</h1>
<p class="txt-c">On this page you can find all voiced NPCs and listen to their lines.</p>

<p class="txt-c">
<i>Looking for a quest in particular? Search it!</i>
</p>

<p class="txt-c"><input id="q_search" class="login-form" type="text" name="searchbar" placeholder="Search quest..."></input></p>

<div class="mod-contents">
	<div id="results_container"></div>
	<?php for ($i = 0; $i < count(${basename(__FILE__, '.phtml').'_quests'}); $i++) : ?>
		<?php $quest = ${basename(__FILE__, '.phtml').'_quests'}[$i]; ?>
		<?php if ($i % 3 === 0) : ?>
			<div class="row mod_list">
		<?php endif ?>
			<div class="col-4">
				<div class="card-wrapper">
				<div class="card q-voice">
					<h3 class="quest-name"><?= $quest->getName(); ?></h3>
					
					<div class="quest-info" class="mb-s mt-s pt-s pb-s">
						<?php foreach ($quest->getNpcs() as $npc) : ?>
						<div class="quest-npcs">
							<p class="txt-c mb-s mt-s"><img class="npc-avatar mt-l" src="dynamic/npcs/<?= $npc->getId() ?>.png" alt="NPC avatar" /></p>
							<p class="txt-c mb-s mt-s pb-l sub-line lb-a"><a href="contents/npc/<?= $npc->getId() ?>"><?= $npc->getName() ?></a></p>
						</div>
						<?php endforeach ?>
						</div>
				</div>
				</div>
			</div>
		<?php if (($i + 1) % 3 === 0) : ?>
			</div>
		<?php endif ?>
	<?php endfor ?>
</div>
