<h1>Mod contents</h1>
<p style="text-align: center;">There are a ton of NPCs in Wynncraft. Here you can find all that have been voiced including with all of their voice lines if you would just like to check out some npc's voice.</p>
<br>

<p style="text-align: center;">
<i>Looking for a quest in particular? Search it!</i>
<br><br>
<!-- <input style="border-left: none; border-right: none; border-top: none;" class="searchQuest" id="searchQ" 
	   name="searchbar" 
	   size="35" maxlenght="200"
		onkeyup="get_input()"
	   type="text" placeholder="Search quest..."/>
</p> -->


<input id="q_search" type="text" name="searchbar" placeholder="Search quest..."><button class="qsearchbtn" type="submit" onclick="get_input()">Search</button></input>

<div>
	<?php for ($i = 0; $i < count(${basename(__FILE__, '.phtml').'_quests'}); $i++) : ?>
		<?php $quest = ${basename(__FILE__, '.phtml').'_quests'}[$i]; ?>
		<?php if ($i % 3 === 0) : ?>
			<div class="row">
		<?php endif ?>
			<div class="col-4">
				<div class="card-wrapper">
				<div class="card npcvoice">
					<h3 class="questName"><?= $quest->getName(); ?></h3>
					
					<div class="questInfo" style="margin-bottom: 0px; margin-top: 0px; padding-top: 0px; padding-bottom: 0px;">
						<?php foreach ($quest->getNpcs() as $npc) : ?>
						<div class="quest-npcs">
							<p style="text-align: center; margin-bottom: 0px; margin-top: 0px;"><img class="npc-avatar" src="dynamic/npcs/<?= $npc->getId() ?>.png" alt="NPC avatar" /></p>
							<p style="text-align: center;
										border-bottom: 1px solid black;
										margin-top: 0px; margin-bottom: 0px;
										padding-bottom: 15px;
							"><a href="contents/npc/<?= $npc->getId() ?>"><?= $npc->getName() ?></a></p>
							<br>
						</div>
						<?php endforeach ?>
						</div>
				</div>
				</div>
			</div>
		<?php if (($i + 1) % 3 === 0) : ?>
			</div>
		<?php endif ?>
	<?php endfor ?>
</div>