<h1>Contributors</h1>
<p style="text-align: center;">A lot of people worked hard on this mod. Take a moment to appreciate their effort and find out who helped.</p>
<?php $currentHighestRole = null; ?>
<div class="row">
<?php foreach (${basename(__FILE__, '.phtml').'_contributors'} as $contributor) : ?>
	<?php
        if ($currentHighestRole !== $contributor->getRoles()[0]->name) :
            //New highest role
	        $currentHighestRole = $contributor->getRoles()[0]->name;
    ?>
    </div> <!-- ending for <div class="row"> -->
    <hr>
	<h2><?= $contributor->getRoles()[0]->name ?><?php if ($contributor->getRoles()[0]->name !== 'Owner') : ?>s<?php endif ?></h2>
<div class="row" id="credits0">
	<?php endif ?>
	<div class="cardwrapper" id="credits1">
	<div class="col-3" id="credits2"><a class="cardlink" href="/cast/<?= $contributor->getId(); ?>">
		<div class="card" id="credits3">
			<img class="avatar" src="dynamic/avatars/<?= $contributor->getAvatarLink(); ?>" alt="Contributor's profile picture" /><br>
			<p class="contributor_name"><strong><?= $contributor->getName(); ?></strong></p>
				<hr> 
				<?php if (!empty($contributor->getLore())) : ?>
				<i><?= $contributor->getLore() ?></i>
				<?php endif ?>
				<ul class="roles">
					<?php foreach ($contributor->getRoles() as $role) : ?>
					<li style="color:#<?= $role->color ?>;"><?= $role->name ?></li>
					<?php endforeach ?>
				</ul>
				<hr>
			</div>
	</a></div>
	</div>
<?php endforeach ?>