<h1>Download Voices of Wynn</h1>

<h2 class="txt-c">Choose your platform</h2>
<p class="txt-c mb-l">
    Voices of Wynn is supported for Forge client and Fabric client.
</p>
<p class="txt-c mb-l">
    Forge version is meant for Minecraft version <code>1.12.2</code>.
</p>

<p class="txt-c mb-l">
    Fabric version is usually meant for the latest Minecraft release version.
    Check the exact version in the download details.
</p>

<div class="mt-l downloads-wrapper">
    <a class="forge-downloads-option" href="/downloads/forge">
        <img class="downloads-option-bg-img" src="images/forge.svg" alt="">
        <span>
            Voices&nbsp;of&nbsp;Wynn<br>
            for<br>
            <strong>Forge</strong>
        </span>
    </a>

    <a class="fabric-downloads-option" href="/downloads/fabric">
        <img class="downloads-option-bg-img" src="images/fabric.png" alt="">
        <span>
            Voices&nbsp;of&nbsp;Wynn<br>
            for<br>
            <strong>Fabric</strong>
        </span>
    </a>
</div>

