<!-- NOTE: inline style tags are being replaced with corresponding classes,
this, however, will not work until better-downloads is merged with newest
styling branch. -->

<?php $downloadDetails = ${str_replace('-', '', basename(__FILE__, '.phtml')).'_download'}; ?>
<h1>Download Voices of Wynn</h1>
<h2><?= $downloadDetails->version; ?></h2>
<p class="txt-c"><span>Released on <?= $downloadDetails->releaseDate->format('jS F Y') ?></span></p>
<table class="dl-details-table">
    <tr>
        <td>Version type</td>
        <td id="release-type" title="<?php
        switch ($downloadDetails->releaseType) {
            case 'alpha':
                echo 'This version comes from an early development and might be very unstable.
It should be only used by testers who are looking for issues to report.';
                break;
            case 'beta':
                echo 'This version is supposed to contain some bugs, but should be relatively stable.
If you decide to use this version and encounter a bug, please report it on our Discord.';
                break;
            case 'pre-release':
                echo 'This version is most likely stable and can be used by regular users, although a rare bug might occur.';
                break;
            case 'release':
                echo 'This version has been thoroughly tested and can be safely used by all users.';
                break;
            case 'patch':
                echo 'This version fixes some bugs that somewhat slip into the previous release.
It doesn\'t contain much new content';
                break;
        }
        ?>"><?= ucfirst($downloadDetails->releaseType) ?></td>
    </tr>
    <tr>
        <td>Mod version</td>
        <td><?= $downloadDetails->version ?></td>
    </tr>
    <tr>
        <td>Wynncraft version</td>
        <td><?= $downloadDetails->wynnVersion ?></td>
    </tr>
    <tr>
        <td>Minecraft version</td>
        <td><?= $downloadDetails->mcVersion ?></td>
    </tr>
    <tr>
        <td>Size</td>
        <td><?= round($downloadDetails->size / 1000000, 2) ?> MB</td>
    </tr>
    <tr>
        <td>Downloaded times</td>
        <td id="download-count"><?= $downloadDetails->downloadedTimes ?></td>
    </tr>
</table>

<div class="txt-c">
    <h3>Download this file</h3>
    <table>
        <tr>
            <td>
                <h4>Direct Download</h4>
            </td>
            <td>
                <h4>Installer and Updater</h4>
            </td>
        </tr><tr>
            <td><strong>Recommended for initial installation.</strong></td>
            <td><strong>Recommended for updating and people with unstable internet connection.</strong></td>
        </tr><tr>
            <td><?= round($downloadDetails->size / 1000000, 2) ?> MB <code>.jar</code> file</td>
            <td>343 KB <code>.exe</code> file</td>
        </tr><tr>
            <td>Download must be restarted from the beginning in case of a failure.</td>
            <td>In case of a failure, the installation can be resumed.</td>
        </tr><tr>
            <td>Keeps antivirus calm.</td>
            <td>
                Might be flagged by your antivirus as malicious.<br>
                <small style="font-size: 0.8rem;"><em>This is a false positive. The installer is open-source and you can check what exactly it does <a href="https://github.com/Team-VoW/500mb_jar_installer" target="_blank">on GitHub</a>.</em></small>
            </td>
        </tr><tr>
            <td>Can be updated using the installer later.</td>
            <td>Can be used to update any existing installation to any published or future version.</td>
        </tr>
        <tr>
            <td>
                <a href="/download/<?= $downloadDetails->id ?>/jar">
                    <button id="download-btn" class="downloadbtn">Download JAR</button>
                </a>
                <div class="txt-c" id="download-started">
                    <p class="txt-c"><b>Your download has started.</b></span></p> 
                    <p class="txt-c report-download-issue"><small>
                        <a href="mailto:team@voicesofwynn.com?subject=Problems%20downloading%20mod%20version%20<?= urlencode($downloadDetails->version) ?>&body=Feel%20free%20to%20include%20any%20additional%20information%20here.%0AOur%20team%20will%20check%20the%20download%20as%20soon%20as%20they%20can.%0A%0AIn%20the%20meantime%2C%20you%20can%20try%20to%20download%20a%20different%20version%20or%20join%20our%20Discord%20and%20ask%20for%20an%20alternative%20download.">
                            Report a problem with this download
                        </a>
                    </small></p>
                </div>
            </td>
            <td>
                <a href="/download/<?= $downloadDetails->id ?>/exe">
                    <button id="install-btn" class="updatebtn">Download Installer</button>
                </a>
                <div class="txt-c" id="install-started">
                    <p class="txt-c"><b>Your download has started.</b></p> 
                    <p class="txt-c report-download-issue"><small>
                        <a href="mailto:team@voicesofwynn.com?subject=Problems%20downloading%20mod%20version%20<?= urlencode($downloadDetails->version) ?>&body=Feel%20free%20to%20include%20any%20additional%20information%20here.%0AOur%20team%20will%20check%20the%20download%20as%20soon%20as%20they%20can.%0A%0AIn%20the%20meantime%2C%20you%20can%20try%20to%20download%20a%20different%20version%20or%20join%20our%20Discord%20and%20ask%20for%20an%20alternative%20download.">
                            Report a problem with this download
                        </a>
                    </small></p>
                </div>
            </td>
        </tr>
    </table>
    <div id="terms" class="txt-c">
        This mod uses a unique identificator to measure the global usage of the mod.<br>
        Any information sent to our servers is anonymous and cannot be traced to any specific user.<br>
        <strong>By downloading and using this mod, you agree to these terms.</strong><br>
        To learn more about what exactly is sent and processed, read the <a href="/faq#data-processing">appropriate section in FAQ</a>.
    </div>
</div>
<hr class="hr-f">
<h2>Changelog</h2>
<article id="changelog">
    <?= $downloadDetails->changelog ?>
</article>

