<h1>Download Voices of Wynn</h1>
<p style="text-align: center;">
    <a href="/downloads/<?= ${basename(__FILE__, '.phtml').'_versions'}[0]->id; ?>"><button class="downloadbtn"><img src="images/download.png" alt="Download icon" width="20px" height="20px" /> Download Latest Version</button></a>
</p>

<hr>
<h2 style="text-align: center;">Older Versions of the Mod</h2>
<p style="text-align: center;">Want an older version of the mod? They are linked below! The oldest are at the bottom and the newest are at the top.</p>

<div class="dlwrapper">
<?php foreach (${basename(__FILE__, '.phtml').'_versions'} as $version) : ?>
    <div style="text-align: center;">
        <h3 style="color:<?php
            switch ($version->releaseType)
            {
                case 'alpha':
                    echo '#FF5000';
                    break;
                case 'beta':
                    echo '#FC8F00';
                    break;
                case 'pre-release':
                    echo '#FCB400';
                    break;
                case 'release':
                    echo '#6ad10a';
                    break;
                case 'patch':
                    echo '#356FF4';
                    break;
            }
        ?>">
            <?= ucfirst($version->releaseType).' '.$version->version; ?>
        </h3>
        <table style="margin:auto;">
            <tr>
                <th>Minecraft version</th><th>Size</th><th>Release Date</th><th>Times Downloaded</th>
            </tr>
            <tr>
                <td><?= $version->mcVersion ?></td>
                <td><?= round($version->size / 1000000, 2) ?> MB</td>
                <td><?= $version->releaseDate->format('jS F Y') ?></td>
                <td><?= $version->downloadedTimes ?></td>
            </tr>
        </table>
        <a href="/downloads/<?= $version->id ?>">
            <button class="downloadbtn">
                <img src="images/download.png" alt="Download icon" width="20px" height="20px"/> More information and download
            </button>
        </a>
    </div>
    <hr class="dlhr">
<?php endforeach ?>
</div>

