<h1>Download Voices of Wynn</h1>
<h4>For <?= ${str_replace('-', '', basename(__FILE__, '.phtml')).'_platform'} ?></h4>
<p class="txt-c mb-l">
    <a href="/downloads/<?= ${str_replace('-', '', basename(__FILE__, '.phtml')).'_versions'}[0]->id; ?>"><button class="downloadbtn"><img src="images/download.png" alt="Download icon" width="20px" height="20px" /> Download Latest Version</button></a>
</p>

<hr class="hr-f">
<h2 class="txt-c">Older Versions of the Mod</h2>
<p class="txt-c mb-l">Want an older version of the mod? They are linked below! The oldest are at the bottom and the newest are at the top.</p>

<div class="download-wrapper mt-l">
<?php foreach (${str_replace('-', '', basename(__FILE__, '.phtml')).'_versions'} as $version) : ?>
    <div class="txt-c">
        <h3 style="color:<?php
            switch ($version->releaseType)
            {
                case 'alpha':
                    echo '#FF5000';
                    break;
                case 'beta':
                    echo '#FC8F00';
                    break;
                case 'pre-release':
                    echo '#FCB400';
                    break;
                case 'release':
                    echo '#6ad10a';
                    break;
                case 'patch':
                    echo '#356FF4';
                    break;
            }
        ?>">
            <?= ucfirst($version->releaseType).' '.$version->version; ?>
        </h3>
        <div class="dl-details-table">
            <table class="m-a dl-table dl-list-table">
                <tr>
                    <th>Wynncraft&nbsp;Version</th>
                    <th><?= ${str_replace('-', '', basename(__FILE__, '.phtml')).'_platform'} ?>&nbsp;Version</th>
                    <th>Size</th>
                    <th>Release&nbsp;Date</th>
                    <th>Times&nbsp;Downloaded</th>
                </tr>
                <tr>
                    <td><?= $version->wynnVersion ?></td>
                    <td><?= $version->mcVersion ?></td>
                    <td><?= round($version->size / 1000000, 2) ?>&nbsp;MB</td>
                    <td><?= str_replace(' ', '&nbsp;', $version->releaseDate->format('jS F Y')) ?></td>
                    <td><?= $version->downloadedTimes ?></td>
                </tr>
            </table>
        </div>
        <a href="/downloads/<?= $version->id ?>">
            <button class="downloadbtn">
                <img src="images/download.png" alt="Download icon" width="20px" height="20px"/> More information and download
            </button>
        </a>
    </div>
    <hr class="dlhr">
<?php endforeach ?>
</div>

