<!DOCTYPE HTML>
<html lang="en">

<head>
    <base href="/" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" />
    <title><?= ${basename(__FILE__, '.phtml') . '_title'} ?></title>
    <meta name="description" content="<?= ${basename(__FILE__, '.phtml') . '_description'} ?>" />
    <!-- Icons -->
    <link rel="apple-touch-icon" sizes="180x180" href="images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="images/wynnvplogo.svg">
    <link rel="icon" type="image/png" sizes="16x16" href="images/wynnvplogo.svg">
    <link rel="manifest" href="site.webmanifest">
    <link rel="mask-icon" href="images/wynnvplogo.svg" color="#a340c4">
    <link rel="shortcut icon" href="images/wynnvplogo.svg">
    <meta name="msapplication-TileColor" content="#7b1a9b">
    <meta name="msapplication-config" content="browserconfig.xml">
    <meta name="theme-color" content="#7b1a9b">

    <!-- Stylesheets -->
    <?php foreach (self::$cssFiles as $cssFile): ?>
        <link rel="stylesheet" type="text/css" href="css/<?= $cssFile ?>.css">
    <?php endforeach ?>
</head>

<body>
    <h1 class="error-header">403 – Forbidden</h1>
    <p><i>It seems like you shouldn't be here...</i></p>
    <p>Maybe your login session has expired. If that's the case, <a href="/login">logging back in</a> should help.</p>
    <img src="images/lucio_where_the_frick_are_we.webp"
        alt="An illustration of two Wynncraft characters looking for something." id="error-picture" class="lb-a" />
    <span class="art-credit lb-a">Art by <a href="https://twitter.com/gleeokenspiel"
            target="_blank">Gleeokenspiel</a></span> <a href="https://voicesofwynn.com" class="return-button">Back to
        Homepage</a>
</body>