<!DOCTYPE HTML>
<html lang="en">

<head>
    <base href="/" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" />
    <title><?= ${basename(__FILE__, '.phtml') . '_title'} ?></title>
    <meta name="description" content="<?= ${basename(__FILE__, '.phtml') . '_description'} ?>" />
    <!-- Icons -->
    <link rel="apple-touch-icon" sizes="180x180" href="images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="images/wynnvplogo.svg">
    <link rel="icon" type="image/png" sizes="16x16" href="images/wynnvplogo.svg">
    <link rel="manifest" href="site.webmanifest">
    <link rel="mask-icon" href="images/wynnvplogo.svg" color="#a340c4">
    <link rel="shortcut icon" href="images/wynnvplogo.svg">
    <meta name="msapplication-TileColor" content="#7b1a9b">
    <meta name="msapplication-config" content="browserconfig.xml">
    <meta name="theme-color" content="#7b1a9b">

    <!-- Stylesheets -->
    <?php foreach (self::$cssFiles as $cssFile): ?>
        <link rel="stylesheet" type="text/css" href="css/<?= $cssFile ?>.css">
    <?php endforeach ?>
</head>

<body>
    <h1 class="error-header">400 – Bad Request</h1>
    <p><i>Hey, I don't want to sound smart, but this doesn't seem correct...</i></p>
    <p>You probably entered some invalid information. Make sure you filled in everything properly and try again.</p>
    <img src="images/lucio_where_the_frick_are_we.webp"
        alt="An illustration of two Wynncraft characters looking for something." id="error-picture" /><br>
    <span class="art-credit">Art by <a href="https://twitter.com/gleeokenspiel" target="_blank"
            rel="noopener noreferrer">Gleeokenspiel</a></span><br>
    <a href="https://voicesofwynn.com" class="return-button">Back to Homepage</a>
</body>

</html>