<h1>FAQ</h1>
<div class="faq-element question-bubble">Which characters are voiced in the mod?</div>
<div class="faq-element answer-bubble">
	<p>Currently, all quest NPCs are voiced. We're working on keeping all quest dialogues up-to-date while adding dialogues to some other NPCs.</p>
	<p>Out of non-quest NPCs, we added voices to Seaskipper Captain and the Talking Mushroom. Other significant NPCs of this kind will be added soon (hopefully).</p>
</div>
<hr>
<div class="faq-element question-bubble">Do you plan to voice all the other NPCs that are in Wynncraft?</div>
<div class="faq-element answer-bubble">
	<p>We're currently adding voices to dialogues of secret discoveries. After that, we'll move to boss altars and dungeon dialogues. After that, we would like to voice white NPCs (NPCs with white nametag), that players are most likely to talk to, but it's not very likely we'll do it for every single one. While adding new voices, we'll need to spend more and more time on keeping already voiced dialogues relevant, which will slow any further progress down.</p>
</div>
<hr>
<div class="faq-element question-bubble">What Minecraft version is needed for the mod to work?</div>
<div class="faq-element answer-bubble">
	<p>The mod was developed for Minecraft version <code>1.12.2</code>. It's also compatible with Wynntils.</p>
</div>
<hr>
<div class="faq-element question-bubble">Can I voice a character and get my voice into the mod?</div>
<div class="faq-element answer-bubble">
	<p>Of course, we'll be more than happy to have another voice actor in our team. Simply <a href="https://discord.gg/kuEK3XH4Y5" target="_blank">join our Discord server</a>. We'll guide you from there.</p>
</div>
<hr>
<div class="faq-element question-bubble">I think that a certain NPC's voice doesn't really fit it.</div>
<div class="faq-element answer-bubble">
	<p>We're always interested in feedback. Some of the roles that were casted when the project was getting started have voice actors, that had much lower standards applied to them. To tell us which NPCs need recasting, simply vote for the individual recordings. You can get to a voting page by going to <a href="contents">Mod Contents</a>, selecting any NPC and clicking its name.</p>
	<p>Apart from upvoting and downvoting recordings, you can also leave comments with specific suggestions. You can get to the comments page from the page, where you can cast votes. Please, keep in mind, that if you're commenig as an unlogged user, your IP address will be stored to prevent abuse.</p>
</div>
<hr>
<div class="faq-element question-bubble">How can I create an account on this webpage?</div>
<div class="faq-element answer-bubble">
	<p>The ability to create accounts is reserved for system administrators. Only people that contributed to the project, either by voicing a character, coding stuff or writing scripts for voice actors can have an account here. The easiest way to get your own account here is <a href="https://discord.gg/kuEK3XH4Y5" target="_blank">joining our Discord server</a> and applying for a role. If you get picked, administrators will create an account for you.</p>
</div>
<hr>
<div class="faq-element question-bubble">I have an account here, but I forgot my password. There's is no "Password recovery" option I can use.</div>
<div class="faq-element answer-bubble">
	<p>If you forgot your password, contact <a href="https://discord.com/users/518828923186970646" target="_blank">Shady#2848</a> on Discord and explain the situation. It'll be much faster, if you contact him from the same Discord account, as the one you used to contribute to the project. Shady is the administrator of this website and will reset your password.</p>
</div>
<hr>
<div class="faq-element question-bubble">I found an offensive, insulting or inappropriate comment, username, or bio on this webpage.</div>
<div class="faq-element answer-bubble">
	<p>There is currently no report option. If you found some content that doesn't seem okay, please, report this to <a href="https://discord.com/users/518828923186970646" target="_blank">Shady#2848</a> on Discord by sending him a direct message.</p>
</div>
<hr>
<div class="faq-element question-bubble">I need to contact an administrator, but I don't have a Discord account and don't want to create one.</div>
<div class="faq-element answer-bubble">
	<p>Alternatively, you can contact us on <a href="mailto:team@voicesofwynn.com" target="_blank">our e-mail</a>. However, keep in mind, that this inbox is not checked as regularly, as our Discord messages.</p>
</div>