<h1>FAQ</h1>
<div class="faq-element question-bubble">How many characters are voiced in the mod?</div>
<div class="faq-element answer-bubble">
	<p>Currently, all quest NPCs are voiced. We’re hard at work keeping all quest dialogues up to date while adding dialogues to non-quest NPCs.</p>
	<p>In addition to quest NPCs, we’ve also added full voice acting for the Seaskipper Captain and the Talking Mushroom. Other significant NPCs will be added soon!</p>
</div>
<hr>
<div class="faq-element question-bubble">Do you plan to voice all NPCs in Wynncraft?</div>
<div class="faq-element answer-bubble">
	<p>We’re currently adding voices to Secret Discoveries. The next thing on our agenda is boss altars and dungeons. After that, it is our hope that we will voice all NPCs with white name tags that players are most likely to talk to. It’s not likely we’ll do every single one.</p>
</div>
<hr>
<div class="faq-element question-bubble">What Minecraft version is needed for the mod to work?</div>
<div class="faq-element answer-bubble">
	<p>The mod was developed for Minecraft version <b style="font-family:monospace;">1.12.2</b>. It's also compatible with Wynntils.</p>
</div>
<hr>
<div class="faq-element question-bubble">Can I voice a character?</div>
<div class="faq-element answer-bubble">
	<p>Of course, we’d be more than happy to have another voice actor. Simply <a href="https://discord.gg/kuEK3XH4Y5" target="_blank">join our discord</a> and we’ll guide you from there.</p>
</div>
<hr>
<div class="faq-element question-bubble">I think that a certain NPC’s voice doesn’t fit.</div>
<div class="faq-element answer-bubble">
	<p>We’re always appreciative of feedback. Some roles were cast early in the mod, when we had much lower standards for performances. One way to signal which NPCs need revoicing is to vote for the recordings in <a href="contents">Mod Contents</a>. Click the name of any NPC and navigate down to the recording of your choice. There, you can also leave comments with feedback for the voice actors. Keep in mind that, if you are not logged into the site, your IP address will be stored to prevent abuse.</p>
</div>
<hr>
<div class="faq-element question-bubble">Some dialogue isn’t playing. Where can I report it?</div>
<div class="faq-element answer-bubble">
	<p>Be aware that some dialogue, such as pre-and-post-quest dialogue is not voiced. However, all dialogue during a quest should be voiced, and if not you should report it. <a href="https://discord.gg/kuEK3XH4Y5" target="_blank">Join our Discord server</a> and navigate down to <b style="white-space:nowrap;">#🚨bugs-and-suggestions💡.</b></p>
</div>
<hr>
<div class="faq-element question-bubble">I saw a login button. How can I create an account?</div>
<div class="faq-element answer-bubble">
	<p>The ability to create accounts is reserved for system administrators. Only contributors – voice actors, coders, or script writers – can have an account. If you apply and are picked for a role, then administrators will create an account for you.</p>
</div>
<hr>
<div class="faq-element question-bubble">I have an account, but forgot my password. There’s no “forgot password” button, so what do I do?</div>
<div class="faq-element answer-bubble">
	<p>If you forgot your password, contact <a href="https://discord.com/users/518828923186970646" target="_blank">Shady#2848</a> on Discord and explain. It’ll be easier if you contact him from the same account you used to apply to the project. Shady will reset your password.</p>
</div>
<hr>
<div class="faq-element question-bubble">I found offensive, insulting, or inappropriate content on this webpage. Where do I report it?</div>
<div class="faq-element answer-bubble">
	<p>Currently, there is no report option. Contact <a href="https://discord.com/users/518828923186970646" target="_blank">Shady#2848</a> on Discord to report inappropriate content.</p>
</div>
<hr>
<div class="faq-element question-bubble">I need to contact an administrator, but I don’t have nor want to create a Discord account. What should I do?</div>
<div class="faq-element answer-bubble">
	<p>You may contact us through <a href="mailto:team@voicesofwynn.com" target="_blank">our email inbox</a>. Keep in mind that this email is not checked as regularly as Discord.</p>
</div>
