<h1>FAQ</h1>

<blockquote>How can I get access to the mod?</blockquote>
<b>
    <p>There are a few ways to get early access to the mod, before it releases to everyone.</p>
    <p>The first option is to voice a character. <a href="https://discord.gg/kuEK3XH4Y5" target="_blank">Join our Discord</a> and apply for one.</p>
    <p>Another option is to become a patron on <a href="https://www.patreon.com/Voices_Of_Wynn" target="_blank">our Patreon</a>. As long as your subscription is active you will have access to certain channel on our <a href="https://discord.gg/kuEK3XH4Y5" target="_blank">Discord server</a> where we post the new versions of the mod. Once you are no longer a patron you will lose access to any new versions.</p>
    <p>The money from the Patreon will go into the mod for things like keeping our Discord bot online, paying for this website and community events to grow the community.</p>
</b>
<hr>
<blockquote>When will the mod release?</blockquote>
<b>
    <p>There is no exact release date. The goal is to finish all quests this year, if we are able to do this largely depends on the amount of auditions we get. When it releases it will be free for everyone.</p>
    <p>Before we're done, you can download and try free demo. It's available on the <a href="/downloads">download page</a>.</p>
</b>
<hr>
<blockquote>Is it allowed to use Voices of Wynn on Wynncraft?</blockquote>
<b>
    Yes.
</b>

<!-- TODO add more questions and answers here -->

