<h1>Voice actor login</h1>
<form method="post">
    <label for="name">E-mail or Username</label>
    <input id="name" type="text" name="name" value="<?= ${basename(__FILE__, '.phtml').'_username'} ?>" <?php
        if (${basename(__FILE__, '.phtml').'_change_password'}) :
    ?>disabled <?php
    endif ?>/><br>

    <label for="password">Password</label>
    <input id="password" type="password" name="password" <?php
        if (${basename(__FILE__, '.phtml').'_change_password'}) :
    ?>value="<?= str_repeat('F', VoicesOfWynn\Models\User::DEFAULT_PASSWORD_LENGTH) ?>" disabled <?php
    endif ?>/><br>
    
    <?php if (${basename(__FILE__, '.phtml').'_change_password'}) : ?>
        <p>You logged in using a temporary password. You need to set a new password before proceeding (<?= VoicesOfWynn\Models\AccountDataValidator::PASSWORD_MIN_LENGTH ?> characters minimum).</p>
        <label for="new-password">New Password</label>
        <input id="new-password" type="password" name="newPassword" /><br>
    <?php endif ?>
    
    <input type="submit" value="Login"/>
</form>
<div><?= ${basename(__FILE__, '.phtml').'_error'} ?></div>
