<h1 class="mb-l">Voice actor login</h1>
<div class="txt-c display-block" >
<form method="post" class="newaccform">
    <label for="name" class="mb-l mr-l lb-a">E-mail or Username</label>
    <input class="login-form mb-d"
           size="35" maxlenght="200"
           id="name" type="text" 
           name="name" value="<?= ${basename(__FILE__, '.phtml').'_username'} ?>" 
           placeholder="Email/Username"
           <?php
        if (${basename(__FILE__, '.phtml').'_change_password'}) :
    ?>disabled <?php
    endif ?>/>

    <div class="pw-box">
    <label for="password" class="mb-l mr-l">Password</label>
    <input class="login-form mb-d"
           size="35" maxlenght="200"
           id="password" type="password" 
           name="password" placeholder="Password"

           <?php
        if (${basename(__FILE__, '.phtml').'_change_password'}) :
    ?>value="<?= str_repeat('F', VoicesOfWynn\Models\Website\User::DEFAULT_PASSWORD_LENGTH) ?>" disabled <?php
    endif ?>/>
    </div>

    <?php if (${basename(__FILE__, '.phtml').'_change_password'}) : ?>
        <p>You logged in using a temporary password. You need to set a new password before proceeding (<?= \VoicesOfWynn\Models\Website\AccountDataValidator::PASSWORD_MIN_LENGTH ?> characters minimum).</p>
        <label for="new-password">New Password</label>
        <input id="new-password" type="password" name="newPassword" />
    <?php endif ?>
    <div class="txt-c error-color"><i><?= ${basename(__FILE__, '.phtml').'_error'} ?></i></div>
    <input 
        class="login-form submit"
        size="20"
        type="submit" value="Login"/>
</form>
</div>

<button class="backbtn" onclick="history.go(-1)">< Go Back</button>