<h2 class="txt-c">Create a new account</h2>
<div class="txt-c display-block">
    <form method="post" class="newaccform">
        <label for="username" class="mb-l lb-a">Display name</label>
        <input class="login-form" type="text" name="name" class="mb-d"/>
        <label for="username" class="mb-l lb-b lb-a">Discord handle</label>
        <input class="login-form" type="text" name="discord" class="mb-d"/>
        <label for="password" class="mb-l lb-b lb-a">Password</label>
        <input class="login-form" type="text" name="password" class="mb-d lb-a" value="<?= ${str_replace('-', '', basename(__FILE__, '.phtml')).'_password'}; ?>" placeholder="Will be generated" readonly/>
        <p class="lb-b mb-s mt-s"><input class="login-form submit" type="submit" value="Create" /></p>
    </form>
</div>
<div><?= ${str_replace('-', '', basename(__FILE__, '.phtml')).'_error'}; ?></div>

<button class="backbtn" onclick="history.go(-1)">< Go Back</button>
