<h2 style="text-align: center;">Create a new account</h2>
<div style="text-align: center;
display: block;" >
    <form method="post" class="newaccform">
        <label for="username">Display name</label><br>
        <input type="text" name="name" /><br><br>
        <label for="password">Password</label><br>
        <input type="text" name="password" value="<?= ${str_replace('-', '', basename(__FILE__, '.phtml')).'_password'}; ?>" placeholder="Will be generated" readonly/><br>
        <br>
        <input type="submit" value="Create" />
    </form>
</div>
<div><?= ${str_replace('-', '', basename(__FILE__, '.phtml')).'_error'}; ?></div>

<button class="backbtn" onclick="history.go(-1)">< Go Back</button>
