<script>var npcId = <?= ${basename(__FILE__, '.phtml').'_npc'}->getId() ?>;</script>

<h1 class="mb-l"><?= ${basename(__FILE__, '.phtml').'_npc'}->getName() ?></h1>

<p class="npc-va-center-img txt-c mb-l">
    <img class="avatar" src="dynamic/npcs/<?= ${basename(__FILE__, '.phtml').'_npc'}->getId() ?>.png" alt="NPC picture" width="200px" height="200px"/>
</p>
<hr class="hr-f">
<p class="txt-c valink-container">
    <strong class="lb-a">Voice actor: </strong>
    <?php if (${basename(__FILE__, '.phtml').'_voice_actor'} === null) : ?>
        <img id="voice-actor-avatar" class="avatarcontents" src="dynamic/avatars/nobody.png" alt="Profile picture" />
        <span id="voice-actor-name" class="lb-b"><i>Nobody</i></span>
        <hr class="hr-f">
    <?php else : ?>
        <a class="valink" href="cast/<?= ${basename(__FILE__, '.phtml').'_voice_actor'}->getId() ?>">
            <img id="voice-actor-avatar" class="avatarcontents" src="dynamic/avatars/<?= ${basename(__FILE__, '.phtml').'_voice_actor'}->getAvatarLink() ?>" alt="Profile picture" />
            <span id="voice-actor-name" class="lb-b"><?= ${basename(__FILE__, '.phtml').'_voice_actor'}->getName() ?></span>
        </a>
        <hr class="hr-f">
    <?php endif ?>
    <?php if (${basename(__FILE__, '.phtml').'_admin'}) : ?>
        <p class="txt-c mb-l"><button id="change-actor-btn">Change</button></p>
        <form id="voice-actor-form">
            <select name="actor" class="mb-d">
                <?php if (${basename(__FILE__, '.phtml').'_voice_actor'} === null) : ?>
                    <option selected disabled hidden></option>
                <?php endif ?>
                <?php foreach (${basename(__FILE__, '.phtml').'_voice_actors'} as $vactor) : ?>
                    <?php if (!${basename(__FILE__, '.phtml').'_voice_actor'} === null && ${basename(__FILE__, '.phtml').'_voice_actor'}->getId() === $vactor->getId) : ?>
                    <option checked value="<?= $vactor->getId() ?>" data-avatar-link="<?= $vactor->getAvatarLink() ?>"><?= $vactor->getName() ?></option>
                    <?php else : ?>
                    <option value="<?= $vactor->getId() ?>" data-avatar-link="<?= $vactor->getAvatarLink() ?>"><?= $vactor->getName() ?></option>
                    <?php endif ?>
                <?php endforeach ?>
            </select>
            <input type="submit" value="Confirm" id="va-confirm-change"/>
        </form>
        <hr class="hr-f">
    <?php endif ?>
</p>

<h3 class="txt-c">Recordings</h3>
<?php foreach (${basename(__FILE__, '.phtml').'_quest_recordings'} as $quest) : ?>

<div class="reccenter">
<section class="table-center">
    <table>
        <tr>
            <th colspan="<?php if (${basename(__FILE__, '.phtml').'_admin'}) : ?>6<?php else : ?>5<?php endif ?>"><?= $quest->getName() ?></th>
        </tr>
	    <?php $recordings = $quest->getNpcs()[0]->getRecordings(); ?>
        <?php foreach ($recordings as $recording) : ?>
        <tr class="voting-audio-box">
            <td class="ws-nw line-count"># <?= $recording->line ?></td>
            <td class="the-recording lb-a">
                <audio controls>
                    <source src="dynamic/recordings/<?= $recording->file ?>" type="audio/ogg">
                    Your browser does not support the OGG audio format.
                </audio>
            </td>
            <td class="voting-buttons">
                <button class="upvote<?php if (in_array($recording->id, ${basename(__FILE__, '.phtml').'_upvoted'})) : ?> clicked<?php endif ?>" data-recording-id="<?= $recording->id ?>" data-npc-id="<?= $recording->npcId ?>">👍 <span><?= $recording->upvotes ?></span></button>
            </td>
            <td class="voting-buttons">
                <button class="downvote<?php if (in_array($recording->id, ${basename(__FILE__, '.phtml').'_downvoted'})) : ?> clicked<?php endif ?>" data-recording-id="<?= $recording->id ?>" data-npc-id="<?= $recording->npcId ?>">👎 <span><?= $recording->downvotes ?></span></button>
            </td>
            <td class="voting-buttons">
                <a href="contents/npc/<?= $recording->npcId ?>/comments/<?= $recording->id ?>"><button class="commentbtn">💬 <span><?= $recording->comments ?></span></button></a>
            </td>
            <td class="voting-buttons">
                <?php if (${basename(__FILE__, '.phtml').'_admin'}) : ?>
                    <button class="delete-recording-btn" data-recording-id="<?= $recording->id ?>">×</button>
                <?php endif ?>
            </td>
        </tr>
        <?php endforeach ?>
    </table>
    <?php if (${basename(__FILE__, '.phtml').'_admin'}) : ?>
        <form method="post" enctype="multipart/form-data" class="new-recording-form">
            <h4>Add new recordings</h4>
            <input name="questId" type="hidden" value="<?= $quest->getId() ?>" />
            <p>
                All files <strong>must</strong> follow the following naming scheme: <code>questname-npcname-linenumber.ogg</code>!
            </p>
            <p>
                Valid names:
                <ul>
                    <li><code>cowfusion-ibele-1.ogg</code></li>
                    <li><code>cropfailure-anast-6.ogg</code></li>
                    <li><code>agravemistake-hangingskeleton-1.ogg</code></li>
                </ul>
                Invalid names:
                <ul>
                    <li><code><b style="color: red">C</b>owfusion-<b style="color: red">I</b>bele-1.ogg</code></li>
                    <li><code>crop<b style="color: red">-</b>failure-anast<b style="color: red">6</b>.ogg</code></li>
                    <li><code>a<b style="color: red">_</b>grave<b style="color: red">_</b>mistak<b style="color: red">e h</b>anging<b style="color: red">S</b>keleton-<b style="color: red">I</b>.<b style="color: red">mp3</b></code></li>
                </ul>
            </p>
            <input name="recordings[]" type="file" accept="audio/ogg" class="recording-input" multiple="multiple" required/>
            <input type="submit" value="Upload"/>
        </form>
        <?php if (isset(${basename(__FILE__, '.phtml').'_uploadErrors'}[$quest->getId()])) : ?>
            <?= ${basename(__FILE__, '.phtml').'_uploadErrors'}[$quest->getId()] ?>
        <?php endif ?>
    <?php endif ?>
</section>
</div>

<?php endforeach ?>

<br>
<button class="backbtn" onclick="history.go(-1)">< Go Back</button>

