<script>var npcId = <?= ${basename(__FILE__, '.phtml').'_npc'}->getId() ?>;</script>

<h1><?= ${basename(__FILE__, '.phtml').'_npc'}->getName() ?></h1>
<br>
<p class="welp"><img src="dynamic/npcs/<?= ${basename(__FILE__, '.phtml').'_npc'}->getName() ?>.png" alt="NPC picture" /></p>
<br><hr>
<p style="text-align: center;">
    <strong>Voice actor: <br></strong>
    <?php if (${basename(__FILE__, '.phtml').'_voice_actor'} === null) : ?>
        <img id="voice-actor-avatar" class="avatarcontents" src="dynamic/avatars/nobody.png" alt="Profile picture" />
        <span id="voice-actor-name"><br><i>Nobody</i></span>
        <hr>
    <?php else : ?>
        <a class="valink" href="cast/<?= ${basename(__FILE__, '.phtml').'_voice_actor'}->getId() ?>">
            <img id="voice-actor-avatar" class="avatarcontents" src="dynamic/avatars/<?= ${basename(__FILE__, '.phtml').'_voice_actor'}->getAvatarLink() ?>" alt="Profile picture" />
            <span id="voice-actor-name"><br><?= ${basename(__FILE__, '.phtml').'_voice_actor'}->getName() ?></span>
        </a>
        <hr>
    <?php endif ?>
    <?php if (${basename(__FILE__, '.phtml').'_admin'}) : ?>
        <p style="text-align: center;"><button id="change-actor-btn">Change</button></p>
        <form id="voice-actor-form">
            <select name="actor">
                <?php if (${basename(__FILE__, '.phtml').'_voice_actor'} === null) : ?>
                    <option selected disabled hidden></option>
                <?php endif ?>
                <?php foreach (${basename(__FILE__, '.phtml').'_voice_actors'} as $vactor) : ?>
                    <?php if (!${basename(__FILE__, '.phtml').'_voice_actor'} === null && ${basename(__FILE__, '.phtml').'_voice_actor'}->getId() === $vactor->getId) : ?>
                    <option checked value="<?= $vactor->getId() ?>" data-avatar-link="<?= $vactor->getAvatarLink() ?>"><?= $vactor->getName() ?></option>
                    <?php else : ?>
                    <option value="<?= $vactor->getId() ?>" data-avatar-link="<?= $vactor->getAvatarLink() ?>"><?= $vactor->getName() ?></option>
                    <?php endif ?>
                <?php endforeach ?>
            </select>
            <input type="submit" value="Confirm" />
        </form>
        <hr>
    <?php endif ?>
</p>

<h3 style="text-align: center;">Recordings</h3>
<?php foreach (${basename(__FILE__, '.phtml').'_quest_recordings'} as $quest) : ?>
<center>
<section  class="table-center">
    <table align="center">
        <tr>
            <th colspan="2"><?= $quest->getName() ?></th>
            <th>👍</th>
            <th>👎</th>
            <th><?php if (!${basename(__FILE__, '.phtml').'_admin'}) : ?>💬<?php endif ?></th>
        </tr>
	    <?php $recordings = $quest->getNpcs()[0]->getRecordings(); ?>
        <?php foreach ($recordings as $recording) : ?>
        <tr>
            <td># <?= $recording->line ?></td>
            <td>
                <audio controls>
                    <source src="dynamic/recordings/<?= $recording->file ?>" type="audio/ogg">
                    Your browser does not support the OGG audio format.
                </audio>
            <td><a<?php if (!isset($_COOKIE['votedFor'.$recording->id])) : ?> class="upvote"<?php endif ?> data-recording-id="<?= $recording->id ?>" data-npc-id="<?= $recording->npcId ?>"><?= $recording->upvotes ?></a></td>
            <td><a<?php if (!isset($_COOKIE['votedFor'.$recording->id])) : ?> class="downvote"<?php endif ?> data-recording-id="<?= $recording->id ?>" data-npc-id="<?= $recording->npcId ?>"><?= $recording->downvotes ?></a></td>
            <td>
                <?php if (${basename(__FILE__, '.phtml').'_admin'}) : ?>
                    <button class="delete-recording-btn" data-recording-id="<?= $recording->id ?>">×</button>
                <?php else : ?>
                    <a href="contents/npc/<?= ${basename(__FILE__, '.phtml').'_npc'}->getId() ?>/comments/<?= $recording->id ?> "class="comment"><?= $recording->comments ?></a>
                <?php endif ?>
            </td>
        </tr>
        <?php endforeach ?>
    </table>
    <?php if (${basename(__FILE__, '.phtml').'_admin'}) : ?>
        <form method="post" enctype="multipart/form-data" class="new-recording-form">
            <h4>Add new recording</h4>
            <input name="questId" type="hidden" value="<?= $quest->getId() ?>" />
            <table>
                <tr><th>File</th><th>Line #</th></tr>
                <tbody class="new-recording-items-container">
                    <tr class="new-recording-item">
                        <td>
                            <input name="recording1" type="file" accept="audio/ogg" class="recording-input" required/>
                        </td>
                        <td>
                            <?php if (empty($recordings)) : ?>
                                <input name="line1" type="number" min="1" max="32767" value="1" class="line-input" required/>
                            <?php else : ?>
                                <input name="line1" type="number" min="1" max="32767" value="<?= $recordings[count($recordings) -1]->line+1 ?>" class="line-input" required/>
                            <?php endif ?>
                        </td>
                    </tr>
                </tbody>
            </table>
            <button class="add-more-recordings-button">Add more</button>
            <input type="submit" value="Upload"/>
        </form>
        <?php if (isset(${basename(__FILE__, '.phtml').'_uploadErrors'}[$quest->getId()])) : ?>
            <?= ${basename(__FILE__, '.phtml').'_uploadErrors'}[$quest->getId()] ?>
        <?php endif ?>
    <?php endif ?>
</section>
</center>
<?php endforeach ?>

<br>
<a href="/contents"><button class="backbtn">< Go Back</button></a>

