--liquibase formatted sql

-- changeset shady:2
CREATE TABLE `faq` (
   `faq_id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `faq_position` tinyint unsigned NOT NULL,
   `faq_visible` tinyint(1) NOT NULL DEFAULT '1',
   `question` text NOT NULL,
   `answer` text NOT NULL
) ENGINE='MyISAM';

INSERT INTO `faq` (`faq_id`, `sorting_order`, `visible`, `question`, `answer`) VALUES
   (1,	1,	1,	'How many characters are voiced in the mod?',	'<p>Currently, all quest NPCs and dungeon NPCs are voiced. We’re working hard to keep all quest and dungeon dialogues up to date while adding voicelines to other NPCs as well, but sometimes, there is is slight change in dialogue that breaks a voiceline here and there.</p>\r\n<p>In addition to quest and dungeon NPCs, we’ve also added full voice acting for the Seaskipper Captain and the Talking Mushroom. Other significant NPCs will be added soon!</p>'),
   (2,	2,	1,	'Do you plan to voice all NPCs in Wynncraft?',	'<p>We’re currently adding voices to Secret Discoveries and Boss Altars. After that, it is our hope that we will voice all NPCs with white name tags that players are most likely to talk to. It’s not likely we’ll manage to do every single one because of dialogue changes.</p>'),
   (3,	3,	1,	'What Minecraft version is needed for the mod to work?',	'<p>The mod is currently developed for Fabric (Minecraft version <b class=\"monospace\">1.21.4</b>).</p>\r\n<p>In the past, it was first developed for Forge (Minecraft version <b class=\"monospace\">1.12.2</b>), but support for Forge has since been dropped.</p>\r\n<p>Voices of Wynn is also compatible with Wynntils.</p>'),
   (4,	4,	1,	'What user data does the mod collect and how are they processed?',	'<p>When you log in to Wynncraft with the mod enabled, it sends a request to our servers to check whether there\'s an update available and also to log some things for analytical purposes.</p>\r\n<p>The main information sent to our servers with this request is a <code>sha256</code> hash of your player UUID. This hash can never be turned back into your UUID and serves as an anonymous and unique identificator of a user.</p>\r\n<p>Because of how HTTP requests work, your IP (or IP of any VPN or Tor exit node used) is also visible to us. This information is also hashed using the same algorithm (server-side this time).</p>\r\n<p>These two pieces of information are stored securely in our database. The hash of your IP address is deleted after 2 days at most, the hash of your UUID is kept permanently, but after two days at most, the timestamp when it was submitted is deleted.</p>\r\n<p>This image probably does a better job at explaining the flow of the whole process:</p>\r\n<img src=\"images/data-processing.svg\" />\r\n<p>In the end, we\'re left with the following statistics:</p>\r\n<ol>\r\n<li>How many players used our mod on any given day.</li>\r\n<li>The total number of unique players who used our mod at least once.</li>\r\n</ol>\r\n<p>The hash of your UUID is kept to not count you into the second statistic more than once.</p>'),
   (5,	5,	1,	'Can I voice a character?',	'<p>Of course, we’d be more than happy to have another voice actor. Simply <a href=\"https://discord.gg/kuEK3XH4Y5\" target=\"_blank\">join our discord</a> and we’ll guide you from there.</p>'),
   (6,	6,	1,	'I think that a certain NPC’s voice doesn’t fit.',	'<p>We’re always appreciative of feedback. Some roles were cast early in the mod, when we had much lower standards for performances. One way to signal which NPCs need revoicing is to vote for the recordings in <a href=\"contents\">Mod Contents</a>. Click the name of any NPC and navigate down to the recording of your choice. There, you can also leave comments with feedback for the voice actors. Keep in mind that, if you are not logged into the site, your IP address will be stored to prevent abuse.</p>'),
   (7,	7,	1,	'Some dialogue isn’t playing. Where can I report it?',	'<p>Be aware that some dialogue, especially dialogue said by most of the white-named NPCs (non-quest NPCs) is not voiced. However, all dialogue related to quests and dungeons should be voiced. If you enabled line reporting after installing Voices of Wynn, you don\'t need to do anything, because the reports will be sent automatically.</p>\r\n<p>If you run into a different issue, <a href=\"https://discord.gg/kuEK3XH4Y5\" target=\"_blank\">join our Discord server</a> and navigate down to <b class=\"ws-nw\">#🙋issues-and-support.</b></p>'),
   (8,	8,	1,	'I saw a login button. How can I create an account?',	'<p>The ability to create accounts is reserved for system administrators. Only contributors – voice actors, coders, or script writers – can have an account. If you apply and are picked for a role, then administrators will create an account for you.</p>'),
   (9,	9,	1,	'I have an account, but forgot my password. There’s no “forgot password” button, so what do I do?',	'<p>If you forgot your password, contact <a href=\"https://discord.com/users/518828923186970646\" target=\"_blank\">@shady_medic</a> on Discord and explain. It’ll be easier if you contact him from the same account you used to apply to the project. Shady will reset your password.</p>'),
   (10,	10,	1,	'I found offensive, insulting, or inappropriate content on this webpage. Where do I report it?',	'<p>Currently, there is no report option. Contact <a href=\"https://discord.com/users/518828923186970646\" target=\"_blank\">@shady_medic</a> on Discord to report inappropriate content.</p>'),
   (11,	11,	1,	'I need to contact an administrator, but I don’t have nor want to create a Discord account. What should I do?',	'<p>You may contact us through <a href=\"mailto:team@voicesofwynn.com\" target=\"_blank\">our email inbox</a>. Keep in mind that this email is not checked as regularly as Discord.</p>');