<?php

namespace VoicesOfWynn\Controllers\Api;

/**
 * Enum for API error codes returned in 400 Bad Request responses
 * See API_ERROR_CODES.md for detailed documentation of each error code
 */
enum ApiErrorCode: string
{
    // General error codes
    case UNKNOWN_ACTION = 'UNKNOWN_ACTION';
    case MISSING_REQUIRED_PARAMETER = 'MISSING_REQUIRED_PARAMETER';
    case INVALID_PARAMETER_TYPE = 'INVALID_PARAMETER_TYPE';
    case INVALID_PARAMETER_VALUE = 'INVALID_PARAMETER_VALUE';
    case INVALID_PARAMETER_FORMAT = 'INVALID_PARAMETER_FORMAT';

    // Bootup Actions error codes
    case INVALID_ID_FORMAT = 'INVALID_ID_FORMAT';

    // Line Reporting error codes
    case INVALID_PARAMETER_LENGTH = 'INVALID_PARAMETER_LENGTH';
    case INVALID_COORDINATE_RANGE = 'INVALID_COORDINATE_RANGE';
    case MISSING_STATUS = 'MISSING_STATUS';
    case INVALID_STATUS_VALUE = 'INVALID_STATUS_VALUE';
    case MISSING_LINES_PARAMETER = 'MISSING_LINES_PARAMETER';
    case INVALID_LINES_TYPE = 'INVALID_LINES_TYPE';
    case EMPTY_LINES_ARRAY = 'EMPTY_LINES_ARRAY';
    case NO_LINES_PROVIDED = 'NO_LINES_PROVIDED';
    case INVALID_NPC_NAME = 'INVALID_NPC_NAME';
    case MISSING_LINE_PARAMETER = 'MISSING_LINE_PARAMETER';
    case INVALID_MINREPORTS_TYPE = 'INVALID_MINREPORTS_TYPE';
    case INVALID_DATE_FORMAT = 'INVALID_DATE_FORMAT';

    // Content error codes
    case MISSING_QUEST_ID = 'MISSING_QUEST_ID';
    case INVALID_QUEST_ID = 'INVALID_QUEST_ID';

    // Discord Integration error codes
    case MISSING_ACTION_PARAMETER = 'MISSING_ACTION_PARAMETER';
    case INVALID_DISCORD_ID = 'INVALID_DISCORD_ID';
    case INVALID_ROLES_JSON = 'INVALID_ROLES_JSON';
}
